name: Build

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: docker
    container:
      image: archlinux:base

    steps:
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm --needed \
            git \
            base-devel

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Test
        run: make test
